module.exports.descriptors = [
    'High-intensity workouts',
'Weight training',
'Yoga classes',
'Peaceful environment',
'Cardio equipment',
'Personal training',
'Strength training',
'Expert coaches',
'Group fitness',
'Energetic atmosphere',
'Spinning classes',
'Endurance focus',
'Pilates sessions',
'Core strengthening',
'Functional fitness',
'Full-body workout',
'Boxing gym',
'High-energy sessions',
'CrossFit training',
'Dynamic routines',
'Aquatic fitness',
'Swimming pool',
'Bootcamp classes',
'Team motivation',
'Wellness center',
'Holistic approach',
'Advanced machines',
'Muscle building',
'Zumba classes',
'Dance cardio',
'HIIT training',
'Fast results',
'Powerlifting gym',
'Heavy lifting',
'Martial arts',
'Self-defense techniques',
'Circuit training',
'Quick routines',
'Meditation room',
'Stress relief',
'Outdoor workouts',
'Nature-inspired training',
'Mindfulness sessions',
'Relaxation techniques',
'Children fitness',
'Fun activities',
'Senior classes',
'Low-impact exercises',
'Nutrition coaching',
'Healthy eating',
'Sports performance',
'Athlete development',
'Dance fitness',
'Rhythmic movements',
'Virtual classes',
'Flexible scheduling',
'Team sports',
'Camaraderie and competition',
'Specialty classes',
'Unique experiences',
'Strength conditioning',
'Power and agility',
'Bodyweight training',
'No equipment',
'Wellness workshops',
'Lifestyle improvement',
'Weight loss programs',
'Sustainable change',
'Recovery sessions',
'Injury prevention',
'Fitness challenges',
'Community support',
'Personal coaching',
'Customized plans',
'Healthy cafe',
'Nutritious snacks',
'Family-friendly',
'All ages welcome',
'Exclusive memberships',
'Premium experience',
]

module.exports.places = [
    'Swimming',
    'Tennis',
    'General',
    'Yoga',
]

